# Generated by Django 3.1.7 on 2021-07-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210718_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ambassador_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
